### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by kyds3k** [KatsuteDev/Background#103]
### Operating System

Ventura 13.2.1

### VSCode Version

1.75.1

### Extension Version

2.4.2

### Issue

I follow the instructions and the background does not change. When trying to follow the instructions for #76 , terminal says:

`chmod: Unable to change file mode on /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer): Operation not permitted`

### How to replicate

1. Install extension
2. Follow instructions for installation and configuration
3. Observe that background does not change

**Comment by Katsute** [comment]
Related #84

**Comment by Katsute** [comment]
Permissions issue, will most likely be fixed by #97

**Comment by Katsute** [comment]
Permissions issue should now be fixed as of [`2.5.0`](https://github.com/KatsuteDev/Background/releases/tag/2.5.0), please open a new issue if this still occurs after the update.
