### ISSUE TITLE
Background doesn't work on archlinux

### ISSUE THREAD

**Issue by Fenriir42** [KatsuteDev/Background#140]
### Operating System

Arch Linux x86_64

### VSCode Version

1.76.2

### Extension Version

2.5.4

### Issue

when i activate the extension or want to upload a background this error message appears
![image](https://user-images.githubusercontent.com/97297209/231213196-030ff72e-852e-4f69-9fb9-c6a981201be8.png)

### How to replicate

just download the extension on arch and you will encounter this error (try on other computer than mine and the probleme is still here)

**Comment by Katsute** [comment]
readonly issue is most likely caused by [snap](https://askubuntu.com/a/919098), try installing vscode using the deb instead https://code.visualstudio.com/download

**Comment by Fenriir42** [comment]
thank you the problem is solved

**Comment by Fenriir42** [comment]
thanks

**Comment by Katsute** [comment]
No problem, I will add this issue to the README so others will be informed.
