### ISSUE TITLE
When opening a folder through VS the wallpaper is diappearing. 

### ISSUE THREAD

**Issue by benedicti0n** [KatsuteDev/Background#155]
### Operating System

Mac M1 Ventura 13.3.1(a)

### VSCode Version

1.78.1(universal)

### Extension Version

2.5.5

### Issue

When i reopen vs code the wallpaper is showing fine in Vs code welcome screen. but when i opening a folder or file the wallpaper is dissapearing.

### How to replicate

https://github.com/KatsuteDev/Background/assets/113491469/07e46c71-d1fb-4956-963e-c7efaada4bf4

**Comment by Katsute** [comment]
This issue might be fixed by #156, update the extension and let me know if the issue still occurs.

**Comment by benedicti0n** [comment]
yes its fixed! thanks and btw i just love this extension❤️

**Comment by Katsute** [comment]
No worries 👍
