### ISSUE TITLE
Adaptive image selection

### ISSUE THREAD

**Issue by fenhl** [KatsuteDev/Background#175]
### Feature

Allow configuring different background image based on whether the window is a remote session and if so, depending on the remote name. Add an API that allows other extensions to swap to a different background image.

### Reason

I have my desktop wallpapers and terminal emulators configured so different images are used depending on the time (in relation to my schedule, so the updates are made by a custom script) and, for terminals, the host of the SSH session. I would like VS Code's background to match this behavior.

**Comment by Katsute** [comment]
Conditional backgrounds will not be added as it is a very niche use case. A new [api](https://github.com/KatsuteDev/Background#-api) has been added instead so you can modify backgrounds using your own extension.
