### ISSUE TITLE
The window background image is not visible in the area of the system buttons

### ISSUE THREAD

**Issue by faseceroo** [KatsuteDev/Background#178]
### Operating System

Windows 10

### VSCode Version

1.80.2

### Extension Version

2.6.1

### Issue

The minimize, restore, and close buttons are obscuring the background image.
![image](https://github.com/KatsuteDev/Background/assets/93630866/a47955e6-287c-46d5-b6e0-88f45b55b77e)

### How to replicate

Setup a Window background image and check top-right corner.

**Comment by Katsute** [comment]
This is a Windows limitation, it is not possible to make those buttons transparent.
