### ISSUE TITLE
Missing background on settings navigation bar

### ISSUE THREAD

**Issue by erlete** [KatsuteDev/Background#276]
### Operating System

Windows

### VSCode Version

1.85.1

### Extension Version

2.9.1

### Issue

The navigation sidebar on the VSCode Settings UI is not affected by the background settings, but rather defaults to the applied theme's color.

![image](https://github.com/KatsuteDev/Background/assets/76848729/e9597064-8c71-4502-90cb-7e05fe1076db)

I have set multiple images, tweaked plenty of background customization settings, but the issue remains unaffected.

### Settings

```json
"background.windowBackgrounds": [
    <hidden for privacy reasons>
],
"background.backgroundOpacity": [
    0.8,
    0.9,
    0.9,
    0.9
],
"background.backgroundSize": [
    "Cover",
    "Cover",
    "Cover",
    "Cover"
],
"background.backgroundBlur": [
    "0.1",
    "0",
    "0",
    "0"
],
"background.backgroundSizeValue": [
    "100%",
    "100%",
    "100%",
    "100%"
],
"background.smoothImageRendering": true,
"background.renderContentAboveBackground": true,
"background.useWindowOptionsForAllBackgrounds": true
```

### How to replicate

1. Install extension
2. Add background images
3. Install & reload
4. Go to Settings (UI)
5. ***Behold!***

**Comment by Katsute** [comment]
This can be fixed by setting the `background.renderContentAboveBackground` option to `false`.

**Comment by erlete** [comment]
> This can be fixed by setting the `background.renderContentAboveBackground` option to `false`.

Absolutely right, it does solve the issue. Should this be an expected behavior, though?

**Comment by erlete** [comment]
Also, any ideas on why the background does not render over the minimized, windowed and close buttons?

![image](https://github.com/KatsuteDev/Background/assets/76848729/057bb1a8-9388-43f9-a8bf-4de255689ca6)

Updated config:

```json
"background.windowBackgrounds": [
    <hidden for privacy reasons>
],
"background.backgroundOpacity": [
    0.8,
    0.8,
    0.8,
    0.8
],
"background.backgroundSize": [
    "Cover",
    "Cover",
    "Cover",
    "Cover"
],
"background.backgroundBlur": [
    "0.1",
    "0.1",
    "0.1",
    "0.1"
],
"background.backgroundSizeValue": [
    "100%",
    "100%",
    "100%",
    "100%"
],
"background.useWindowOptionsForAllBackgrounds": true,
"background.renderContentAboveBackground": false,
"background.smoothImageRendering": false
```

**Comment by Katsute** [comment]
> Absolutely right, it does solve the issue. Should this be an expected behavior, though?

This is expected behavior, setting backgrounds to transparent causes overlap issues, especially with sticky scrolling.

> Also, any ideas on why the background does not render over the minimized, windowed and close buttons?

Intended behavior caused by Windows https://github.com/KatsuteDev/Background/issues/178.

**Comment by erlete** [comment]
Perfect then, thanks for the support!
