### ISSUE TITLE
Changing background opacity inversely changes foreground opacity

### ISSUE THREAD

**Issue by StephenSHorton** [KatsuteDev/Background#300]
### Operating System

macOS Sonoma 14.2.1 (23C71)

### VSCode Version

1.85.1 (Universal)

### Extension Version

v2.9.4

### Settings

"background.windowBackgrounds": [
    "https://i.redd.it/5qqn87uc36161.jpg",
    "https://i.redd.it/ms7gbu8c36161.jpg",
    "https://i.redd.it/s8y63hod36161.jpg"
  ],
  "background.backgroundChangeTime": [60, 0, 0, 0],
  "background.backgroundOpacity": [0.9, 0.9, 0.9, 0.9]

### Issue

Changing background opacity inversely changes foreground opacity. I expected the background opacity to only affect the background. It appears that the foreground, specifically the editor text becomes more transparent as the background becomes more opaque.

### How to replicate

Change the window background opacity for example, to 0.2

**Comment by Katsute** [comment]
This is intentional, the opacity option changes the UI opacity rather than the background opacity.

An opacity of 1 means the background is fully invisible, while an opacity of 0 means the background is fully visible.

**Comment by StephenSHorton** [comment]
@Katsute thanks for explaining.
