### ISSUE TITLE
flatpak issue

### ISSUE THREAD

**Issue by Baturax** [KatsuteDev/Background#314]
### Operating System

void linux

### VSCode Version

flatpak version 1.88.0

### Extension Version

2.10.2

### Issue

when i install this,  it wants to copy file and when i click yes it gives error.
![image](https://github.com/KatsuteDev/Background/assets/68316278/ad5dbda9-d6f5-4b3a-a2e2-29db43dd3f4a)
![image](https://github.com/KatsuteDev/Background/assets/68316278/b34c07c1-2088-4fed-9062-4f56b696489d)

### How to replicate

https://github.com/KatsuteDev/Background/assets/68316278/358f4bd4-dfb2-4158-a12b-959b4cb397d4

**Comment by Katsute** [comment]
This is likely a permissions issue with flatpak, try installing using deb or rpm: https://code.visualstudio.com/download

**Comment by polygonnedpotato** [comment]
> This is likely a permissions issue with flatpak, try installing using deb or rpm: https://code.visualstudio.com/download

This would cause the same error. these packages are installed system-wide, so doing that would require admin as-well.

the only way to install without admin, is by using a vscode tarball.

**Comment by Katsute** [comment]
Yeah, tarball might be the only solution for this. Usually the extension would fallback to sudo to write to these directories, however it seems like this Linux distro doesn't have the usual sudo apps.

**Comment by Baturax** [comment]
yes tarball is best choice but it would be good for flatpak too when i run musl bsed distro i have install vscode from fflatpak

**Comment by Katsute** [comment]
This isn't something that can be fixed because it doesn't use the usual sudo apps that the other linux distros use, as a workaround you can try adding write permission manually to the directory in the error.
