### ISSUE TITLE
I hope the image can be displayed in both the editor and the panel area

### ISSUE THREAD

**Issue by you-hengh** [KatsuteDev/Background#320]
### Feature

I hope the image can be displayed in both the editor and the panel area

### Reason

Because the sidebar area shows images, the text in Explorer looks blurry, so I had to use the edit area background instead of the global background

Now I want to support the ability to display an image in both the editing area and the panel area, is that okay?

**Comment by Katsute** [comment]
This extension already supports adding background images to both the editor and panel.

**Comment by you-hengh** [comment]
> This extension already supports adding background images to both the editor and panel.

No, I don't think you understand what I mean. I mean, an image that spans the edit area and the panel area

Like this:

![2024-04-23_23-42-48](https://github.com/KatsuteDev/Background/assets/34816426/dac5db43-7fd2-482e-bee5-e4b03368decb)

**Comment by Katsute** [comment]
This is not something that can easily be added to this extension.

For now, you can use the `renderContentAboveBackground` option and increase the opacity to improve readibility of the sidebar.

**Comment by you-hengh** [comment]
> This is not something that can easily be added to this extension.
> 
> For now, you can use the `renderContentAboveBackground` option and increase the opacity to improve readibility of the sidebar.

Thank you for your reply. It would be nice to be able to support such a setting one day, thank you.
