### ISSUE TITLE
 Provide shortcut keys or buttons to quickly switch background images

### ISSUE THREAD

**Issue by tryfore** [KatsuteDev/Background#380]
### Feature

Sometimes I don’t like the current picture and want to be able to quickly switch to the next picture.

### Reason

Sometimes I don’t like the current picture and want to be able to quickly switch to the next picture.

**Comment by Katsute** [comment]
Unfortunately, there isn't a way to add this feature, the extension and actual background exist in separate processes that cannot communicate with each other; this is also the reason that a reinstall is required whenever changes are made to background settings.
