### ISSUE TITLE
Separate functionality for each side bar

### ISSUE THREAD

**Issue by Chino-chan** [KatsuteDev/Background#387]
### Feature

Hello, I would like to suggest, if it's even possible to accomplish, to make each side bar (Primary sidebar & Secondary Side bar) have its own separate background configuration (image, opacity, etc).

Currently, you can only configure "Side panel" as a single option and it will affect both. In my case, I set up a folder with images, however to my surprise, each panel presents a different picture, so I guess it may be possible to achieve this, but I don't know. I personally would like to have a different opacity on the left for the menu/file explorer etc and a separate one on the right.

![CH9qpweNdB](https://github.com/user-attachments/assets/dc0658a4-9cda-4e3a-a934-17a513bf63fc)

Thank you

### Reason

Because it would allow even further customization and because I like it and so will someone else, probably.

**Comment by Katsute** [comment]
This would be difficult to add without breaking the current sidebar behavior. I also don't think most people would have a different L/R setting and would find the separation of these an inconvenience.

**Comment by uvita2399** [comment]
>would find the separation of these an inconvenience.

Hmmm I don't know, I personally would like to have an image in the secondary bar only, so the primary bar with the file is clearer. However, if it's difficult then it's difficult. Thank you for replying and keep up the good work.
