### ISSUE TITLE
Part of the title bar does not apply background image

### ISSUE THREAD

**Issue by Nanome203** [KatsuteDev/Background#394]
### Operating System

Windows 11

### VSCode Version

1.92.2

### Extension Version

3.0.0

### Issue

This part does not have background image:

![image](https://github.com/user-attachments/assets/f67d1b75-844d-4adb-875a-a0805de11f3a)

### How to replicate

I used the Window option to apply background

**Comment by Katsute** [comment]
This is a windows limitation, it is not possible to make those buttons use the background.
