### ISSUE TITLE
Working was stopped

### ISSUE THREAD

**Issue by Rishav07-05** [KatsuteDev/Background#403]
### Checks

- [X] I have checked [existing issues](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22).
- [X] I have checked the [help page](https://github.com/KatsuteDev/Background/blob/main/HELP.md).
- [X] This is actually a bug and not a feature.
- [X] I am using the latest extension version.

### Operating System

linux 6.2.0-39-generic

### VSCode Version

1.92.2

### Extension Version

3.0.0

### Settings

```json
{
    "windowBackgrounds": [
        "/home/rishav/Downloads/wallpaperflare.com_wallpaper.jpg"
    ],
    "editorBackgrounds": [],
    "sidebarBackgrounds": [],
    "panelBackgrounds": [],
    "backgroundAlignment": [
        "Center Center",
        "Center Center",
        "Center Center",
        "Center Center"
    ],
    "backgroundAlignmentValue": [
        "50%",
        "50%",
        "50%",
        "50%"
    ],
    "backgroundBlur": [
        "0",
        "0",
        "0",
        "0"
    ],
    "backgroundOpacity": [
        0.1,
        0.1,
        0.1,
        0.1
    ],
    "backgroundRepeat": [
        "No Repeat",
        "No Repeat",
        "No Repeat",
        "No Repeat"
    ],
    "backgroundSize": [
        "Cover",
        "Cover",
        "Cover",
        "Cover"
    ],
    "backgroundSizeValue": [
        "100%",
        "100%",
        "100%",
        "100%"
    ],
    "backgroundChangeTime": [
        0,
        0,
        0,
        0
    ],
    "autoInstall": false,
    "renderContentAboveBackground": false,
    "useInvertedOpacity": false,
    "smoothImageRendering": false,
    "settingScope": "Global",
    "CSS": ""
}
```

### Settings Verification

- [ ] I have made sure to remove any sensitive or personal information from the above input.

### Issue

As i shifted from windows to linux os (Zorin) it stopped working.

### How to replicate

simply try to login vs code and start extention in linux based distros

**Comment by Katsute** [comment]
Does it show an error message when running the install command? Please also let me know how you are installing vscode (snap, rpm/deb, apk, etc.)

**Comment by Rishav07-05** [comment]
No, it doesn't shows any error message when running the install command but when we try to add file to glob it doesn't provide anything in the workspace. I am using the flathub package management system for installing.

**Comment by Katsute** [comment]
The extension seems to encounter permissions issues when using flatpak, try installing vscode using deb.
