### ISSUE TITLE
Support different backgrounds for light mode and dark mode

### ISSUE THREAD

**Issue by Spitfire1900** [KatsuteDev/Background#404]
### Checks

- [X] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [X] I have checked that this feature does not already exist.
- [X] I am using the latest extension version.

### This is a Feature

- [X] This is a feature request and not a bug report.

### Feature

Support having different settings for light mode and dark mode.

E.g.
```json
"background.light_mode": {
  "windowBackgrounds": []
},
"background.dark_mode": {
  "windowBackgrounds": []
}
```

### Reason

I have a preferred image for when VSCode is using a light theme and when it's using a dark theme.

**Comment by Katsute** [comment]
This one wouldn't be possible to add, it would likely break everyone's existing settings if the change was made. Changing themes also doesn't trigger a reload, so the backgrounds wouldn't be able to automatically update unless the install command was manually run by the user.

You can use [vscode profiles](https://code.visualstudio.com/docs/editor/profiles) to have different settings for light & dark.
