### ISSUE TITLE
Feature req: Don't use a background used by other windows

### ISSUE THREAD

**Issue by alanmun** [KatsuteDev/Background#413]
### Checks

- [X] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [X] I have checked that this feature does not already exist.
- [X] I am using the latest extension version.

### This is a Feature

- [X] This is a feature request and not a bug report.

### Feature

I would love a setting that makes it so that no two VS Code windows can use the same background at once. 

### Reason

This would give me an easy way to identify which opened project is which at a quick glance by identifying the background of the window. When ALT+TABbing in Windows, the small icons for each window display the backgrounds, making it very quick to ID which project I want to click on while working. Plus, its just nice to be able to ensure two windows aren't duplicating the same background when you have multiple pretty backgrounds installed.

**Comment by Katsute** [comment]
This _can_ be achieved by using the auto install option along with either environment variables or the workspace setting scope option. Refreshing either window however will cause it to use the background of whatever was updated last. The install command is global, there is no possible way to make it separate for each window.

**Comment by alanmun** [comment]
Is it possible to install a specific background, when you have 3 backgrounds defined? Because that would work for me + turning off the background shuffle

**Comment by Katsute** [comment]
There isn't an option to select a specific background when installing, but you can use env vars or workspace specific settings so it only installs backgrounds set for that workspace. It would however reset to the most recent installed on if you refresh any of the windows, since installs are global and affect all windows.

**Comment by alanmun** [comment]
> There isn't an option to select a specific background when installing, but you can use env vars or workspace specific settings so it only installs backgrounds set for that workspace. It would however reset to the most recent installed on if you refresh any of the windows, since installs are global and affect all windows.

Could you add an example to the docs of how to set env vars to achieve this? I cannot figure it out

**Comment by Katsute** [comment]
https://github.com/KatsuteDev/Background#environment-variables outlines the variables we have built-in

To use backgrounds saved in a project folder you can add `${vscode:workspace}` to use the directory of the current opened project folder.

Example: using path `${vscode:workspace}/backgrounds/**` would include all images in the `background` folder in the current project directory
