### ISSUE TITLE
Manual Background Change

### ISSUE THREAD

**Issue by AtTheZenith** [KatsuteDev/Background#414]
### Checks

- [X] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [X] I have checked that this feature does not already exist.
- [X] I am using the latest extension version.

### This is a Feature

- [X] This is a feature request and not a bug report.

### Feature

Add a button to manually cycle through the installed backgrounds.

### Reason

Instead of manually installing new backgrounds, have a button that cycles through the installed background, so that you can change the background quickly when you get tired of one.

**Comment by Katsute** [comment]
You can use the **Time** option in the menu to automatically cycle between images

**Comment by AtTheZenith** [comment]
But sometimes you want to keep one wallpaper for longer. 🤷

**Comment by Katsute** [comment]
A feature similar to this was discussed in https://github.com/KatsuteDev/Background/issues/380, it isn't possible for the extension menu to communicate with the background so a manual change isn't possible. If you want to keep the background for longer, you can use a higher timer value.

**Comment by AtTheZenith** [comment]
So the background is embedded in VSCode to the point you can't edit it in real-time is what you're saying.

I guess I'll stick to setting the interval timer to 99999999 and [> Developer: Reload Window] ; it provides the closest functionality.

**Comment by Katsute** [comment]
> So the background is embedded in VSCode to the point you can't edit it in real-time is what you're saying, but then how does the background auto-change work?

Yes, this is exactly how it works.

When you use the install command it actually installs **all** backgrounds into an array and on load it just pulls a random one out of that array; this is how it is able to load multiple backgrounds without needing a reinstall or direct access to the extension.

**Comment by AtTheZenith** [comment]
If it's installed as an array, then how come you can't access it from the menu?

**Comment by Katsute** [comment]
The extension menu and background loader exist in two separate processes, it isn't possible to pass information between them. The extension does not have access to modify VSCode's css, and the code that this extension uses to install the background css into the IDE does not have access to the extension interface.

**Comment by AtTheZenith** [comment]
If you're willing to add a communication system, then add a buffer file that passes information/commands in which the two processes read from 🤯

**Comment by Katsute** [comment]
The part of the code that actually adds the backgrounds only has access to the standard web functions, it isn't able to use the node ones. At the end of the day it is basically a browser extension injected into VSCode.

Closing this for now since there isn't really a way to add it. May revisit this in the future as this isn't the first time such a feature has been requested.
