### ISSUE TITLE
to add a live background

### ISSUE THREAD

**Issue by SachinCoder11** [KatsuteDev/Background#420]
### Checks

- [x] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [x] I have checked that this feature does not already exist.
- [x] I am using the latest extension version.

### This is a Feature

- [x] This is a feature request and not a bug report.

### Feature

add option of live walpapper 

### Reason

it will look cool

**Comment by Katsute** [comment]
For a 'live' wallpaper you can add a gif image as a background

**Comment by SachinCoder11** [comment]
👍

**Comment by SachinCoder11** [comment]
Okay
