### ISSUE TITLE
Manual opacity control

### ISSUE THREAD

**Issue by Errornkc24** [KatsuteDev/Background#423]
### Checks

- [x] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [x] I have checked that this feature does not already exist.
- [x] I am using the latest extension version.

### This is a Feature

- [x] This is a feature request and not a bug report.

### Feature

There should be manual opacity control like from 0% to 100% not like inverted opacticy 0 or 1 type. It useful like users can adjust like wise that they can see the background also clearly and the text area also so it looks cool.

### Reason

It is useful for those who want the background clear and also they can see the text area clearly.

**Comment by Katsute** [comment]
This is already supported, you can enter a decimal for those values between 0 and 1. There is also a toggle in the more options menu to invert these numbers if you prefer.
