### ISSUE TITLE
Add config for text opacity

### ISSUE THREAD

**Issue by JosephArifin** [KatsuteDev/Background#429]
### Checks

- [x] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [x] I have checked that this feature does not already exist.
- [x] I am using the latest extension version.

### This is a Feature

- [x] This is a feature request and not a bug report.

### Feature

I would like to see a feature where we can change how opaque the text in our editors. Just how we can change the opaqueness of the background image, just one for the text in our editor. More specifically, I want my text to be clearer.

### Reason

I want to be able to see my text clearly while still having a nice background image.

**Comment by Katsute** [comment]
The text has no opacity set, the visibility is solely based on how opaque the background is.
