### ISSUE TITLE
Scrollable wallpapers

### ISSUE THREAD

**Issue by zmorano1797** [KatsuteDev/Background#433]
### Checks

- [x] I have checked [existing feature requests](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22).
- [x] I have checked that this feature does not already exist.
- [x] I am using the latest extension version.

### This is a Feature

- [x] This is a feature request and not a bug report.

### Feature

Scrollable wallpapers for the editor.

### Reason

So that I can have anime woman as my wallpaper 👍 ![Image](https://github.com/user-attachments/assets/6902be8f-ab98-4b05-abde-f2f8210d380b)
![Image](https://github.com/user-attachments/assets/18b600bc-4c42-425d-8a0a-db479e035ff1)

**Comment by Katsute** [comment]
Not possible unfortunately because of how VSCode handles 'scrolling' https://github.com/KatsuteDev/Background/issues/273#issuecomment-1879913948
