### ISSUE TITLE
Background Slider

### ISSUE THREAD

**Issue by saman3230** [KatsuteDev/Background#47]
### Feature

Hi There

Please Add Background slider feature to this great extension 

For Example : background in images folder change after 5 min

### Reason

This Feature will make working with VSCODE more interesting, and it will also make this plugin more complete than before

**Comment by Katsute** [comment]
Do you mean check for new backgrounds every 5 mins? or change the current background image?

**Comment by saman3230** [comment]
Hi and thanks for your answer

yes , change the current background image

**Comment by saman3230** [comment]
Hello and special thanks for your wonderful plugin, can we see the background slider feature in the near future?
