### ISSUE TITLE
Blur makes background image disappear or won't work

### ISSUE THREAD

**Issue by CarterSnich** [KatsuteDev/Background#53]
### Operating System

Linux (Manjaro KDE)

### VSCode Version

1.72.2 (VSCodium)

### Extension Version

2.0.2

### Issue

Blur sometimes won't work, and sometimes make the background disappear. 

Blur 0
Opacity 0.5
![image](https://user-images.githubusercontent.com/52433531/198858399-5999c4cf-eca5-418e-8554-0a404a3944b9.png)

Blur 2
Opacity 0.5
![image](https://user-images.githubusercontent.com/52433531/198858467-55042c5e-67cb-4f60-bd0e-a4a61904d798.png)

Blur 4 (sometimes value of 2 also makes the bg disappear)
Opacity 0.5
![image](https://user-images.githubusercontent.com/52433531/198858493-12d779ce-e207-442e-a6ff-326f207201b0.png)

### How to replicate

Set these values:
![image](https://user-images.githubusercontent.com/52433531/198858506-474c5f5c-0126-40f9-a37d-c4a0b71b91f6.png)

**Comment by Katsute** [comment]
The blur property only accepts css units, for example: `0`, `50px`, `1rem` ; it does not accept whole numbers (except `0`) or percentages.

I was not able to replicate the disappearing background issue.

**Comment by CarterSnich** [comment]
Okay. It works now. For some reason, I have to explicitly do *Background: Install* and *Background: Reload*, even after clicking the reload button on the notification that appears after changing some value (on the command palette). This now can  closed.
