### ISSUE TITLE
Disable backgrounds for editor subwindow on certain filetypes

### ISSUE THREAD

**Issue by lovernj** [KatsuteDev/Background#55]
### Feature

When the currently open editor window matches a glob pattern (or a regex), turn off background customizations or set the opacity to 100%. Alternatively, a command palette option to set the opacity to 100% for the current editor window only. 

### Reason

My workflow heavily depends on editing and compiling $\LaTeX$ documents, which output as PDF. Having a pdf available to quickly check how code has compiled is super useful, but when this extension sets the opacity of the pdf viewer to <100%, the colors get funky and it doesn't resemble the final print as well. Being able to visually disable this extension for specific editor windows, or to start by having the extension disabled for those windows would be useful.

**Comment by lovernj** [comment]
Just thinking about how you'd do this... Maybe add a special CSS id to the global CSS, kind of like what's going on in `src/extension.ts`, something like 
```css
#fullopac {
    opacity: 100%;
}
````
that overrides the opacity set by the class? Not sure how you'd get the currently active editor window, I'm not familiar with vscode api

**Comment by Katsute** [comment]
This issue is actually caused by how the extension renders backgrounds, I will try and see if I can get the background to render under images and pdfs.

https://stackoverflow.com/a/24577245

**Comment by Katsute** [comment]
@mashiro-san create a new branch fix background layering
