### ISSUE TITLE
EPERM operation not permitted when Background:Install

### ISSUE THREAD

**Issue by Party-Pie** [KatsuteDev/Background#84]
### Operating System

Linux

### VSCode Version

1.74.2

### Extension Version

2.4.0

### Issue

![image](https://user-images.githubusercontent.com/107540357/210403071-318e7278-23c7-4d6e-b757-639ae2e177b4.png)  
Maybe it's because that command runs without sudo priviledges, or maybe that file that is supposed to get modified doesn't have the right permissions I don't know

### How to replicate

View -> Command palette -> Background:Install

**Comment by Katsute** [comment]
I'm not sure if its possible to elevate that command with sudo, since it's contained within the vscode process. Have you tried launching vscode as admin?

**Comment by Party-Pie** [comment]
tried running ```sudo code --no-sandbox --user-data-dir "/usr/share/code/``` (the only way of opening vscode as administrator in linux), but I got a white screen.  
Searching a little bit on the internet and found out that white screen was a vscode bug that has already been reported, there were "solutions" to that error but none of them really worked. I'll have to wait until vscode updates and fixes that problem. When they do so I'll try your solution and I'll write here wether it worked or not

**Comment by cjwijtmans** [comment]
I will not open vscode as admin, ever. There needs to be a different fix.

**Comment by Katsute** [comment]
There is a couple of reasons that makes this issue tricky to solve:

 1. **How this extension operates**

    Writing CSS directly to VSCode is not something that the extension API natively offers, background extensions like mine have had to resort to overwriting the VSCode UI script inside the programs folder to overcome these limitations.

 2. **Extension host permissions**

    All extensions run inside the VSCode extension host and inherit all the permissions of that host. As stated previously, this extension overwrites the UI script, meaning the extension host needs permission to write in the programs directory. 

    VSCode obviously does not grant us such a permission.

    * Windows does not seem to have a write issue as long as you have an admin account
    * Mac protects this directory but there is a feasible workaround (see #76)
    * Linux seems to also protect this directory but there is no known workaround at the moment

 3. **Node limitations**

    Nearly all VSC extensions are js/node based and use methods from node libraries. This particular extension uses `fs` for write and chmod operations to make backgrounds work. Node can't grant itself any permissions other than what VSC allows.

    The extension that you linked, [GlassIT-VSC](https://github.com/hikarin522/GlassIt-VSC), is not subject to any of these restrictions because it runs C# code outside the extension host.

 4. **Lack of linux users**

    Above all, I do not have access to a linux machine and the lack of linux users using this extension makes it very difficult to diagnose and develop workarounds for issue like this.

    Any solution would require some kind of workaround (similar to #76), this extension simply does not have permission.

**Comment by cjwijtmans** [comment]
1. I understood that, file a feature request for vs code I guess? Nothing should write to that folder except for an install/update.
2. I do not want anything running in admin, not the extension either. 
3. That is not how the extension should work though. VSCode should allow extensions to provide CSS for theming.
4.  this is not really OS specific. App should not write in that folder on no OS.

**Comment by Katsute** [comment]
Adding backgrounds to VSCode natively is a highly requested feature, but they seem to have no interest in actually adding such a popular feature (see https://github.com/microsoft/vscode/issues/84120).

I've tried injecting CSS directly into VSCode, but this is simply not possible because the extension host and UI run in separate threads.

Theoretically we could outsource the write to a separate program (like how [GlassIt-VSC](https://github.com/hikarin522/GlassIt-VSC) does it) but it's not really ideal.

For the time being it's going to need some hacky workaround (similar to #76) until a feasible solution is discovered.

**Comment by Katsute** [comment]
https://www.npmjs.com/package/@vscode/sudo-prompt

https://www.npmjs.com/package/sudo-prompt

https://www.npmjs.com/package/@mh-cbon/sudo-fs

Possibly use [`child_process`](https://nodejs.org/api/child_process.html) in conjunction with `sudo` to run a node script.

**Comment by Katsute** [comment]
As of [`2.5.0`](https://github.com/KatsuteDev/Background/releases/tag/2.5.0) this extension will now prompt for admin permission to install the background if the regular install fails. Please open a new issue if the update does not fix this issue.
