### ISSUE TITLE
Background won't disappear

### ISSUE THREAD

**Issue by TheUruz** [KatsuteDev/Background#93]
### Operating System

Windows10

### VSCode Version

1.74.3

### Extension Version

Version: 1.74.3 (system setup) Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T16:59:02.252Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Issue

Even after deleting a url from extension settings it keeps showing up as a window background. i tried uninstall it and reload, it seems to work (even though not always) but then it shows up again. it looks like it's cached somewhere...

### How to replicate

- add a background with the procedure listed in the extension readme using an url as source img
- delete the image url from settings.json at the key "background.windowBackgrounds"
- reload either by reloading whole vscode window or by using the extension reload.

after those steps the image is likely to stay. if it doesn't try close and reopen your editor to see it there again (not in the background.windowBackgrounds but as the actual ide background)

**Comment by Katsute** [comment]
The reload command doesn't actually reinstall background changes, it just refreshes the window and rerandomizes the existing backgrounds.

Any and all configuration changes require you to run the install/uninstall command to take effect.

The issue of backgrounds still appearing after an uninstall is an extremely rare issue caused by VSCode refreshing the window before this extension finishes uninstalling. Reopening code usually fixes this issue.

**Comment by TheUruz** [comment]
i did a uninstall after removing it manually. shall i try something else?

**Comment by Katsute** [comment]
Have you tried removing the background from the menu? This is the recommended way to remove backgrounds.

1. Open the background file list
2. Select the path to modify
3. Set the value to empty
4. Reinstall

![#52](https://raw.githubusercontent.com/KatsuteDev/Background/main/assets/delete.gif)

**Comment by Katsute** [comment]
Please try again using the latest extension version `2.5.1`, some changes were made that might address this issue.

**Comment by Katsute** [comment]
Closed due to inactivity. Please open a new issue if the problem still occurs.
